Repository paw-ong/final-pawong-frontend, pull requests merged in 2025-06, with the labels that each got.

#57 [fix] 파일 경로 수정: 'lostanimal'을 'lostAnimal'로 변경
  src/App.jsx
Labels: 🐞 BugFix

#52 [PW-51] 북마크 정보를 api로 개별 card에서 조회
  src/components/pet/card/LostAnimalCard.jsx
Labels: 🔨 Refactor

#71 [PW-69] 프론트엔드 배포 최적화 및 유사동물 loader 구현
  Dockerfile
  src/components/common/LostCardSpinner.css
  src/components/common/LostCardSpinner.jsx
  src/pages/lostAnimal/LostAnimalDetail.jsx
  vite.config.js
Labels: ⏱️Enhancement, ✨ Feature

#77 [PW-70] 이미지 없을 경우에 default 이미지
  src/assets/images/lostpost/default.png
  src/components/chat/ChatRoom.jsx
  src/components/chat/ChatRooms.jsx
  src/components/chat/ChatRoomsByPost.jsx
  src/components/pet/card/LostAnimalCard.jsx
  src/pages/adoptionAnimal/AdoptionDetail.jsx
  src/pages/lostAnimal/LostAnimalCreate.css
  src/pages/lostAnimal/LostAnimalCreate.jsx
  src/pages/lostAnimal/LostAnimalDetail.jsx
  src/pages/lostAnimal/LostAnimalUpdate.jsx
Labels: 🐞 BugFix

#78 [PW-75] 구조동물 상세보기 페이지 분리
  src/App.jsx
  src/components/pet/card/LostAnimalCard.jsx
  src/pages/lostAnimal/LostAdoptionDetail.jsx
Labels: ✨ Feature
